services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/Documents/sonarr/config:/config
      - /mnt:/downloads/sonarr #optional
      - ${HOME}/Downloads/torrents:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
