services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/Documents/jackett/config:/config
      - ${HOME}/Documents/jackett/downloads:/downloads
    ports:
      - 9117:9117
      - 8191:8191
    restart: unless-stopped
