services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
      #    user: 127:135
    user: 1000:1000
    group_add:
      - "104"
    network_mode: 'host'
    volumes:
      - ${HOME}/Documents/jellyfin/config:/config:z
      - ${HOME}/Documents/jellyfin/cache:/cache
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: /mnt/Videos
        target: /media
    devices:
      - /dev/dri:/dev/dri
        #- /dev/dri/renderD128:/dev/dri/renderD128    
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.local.lan
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp

