services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/Documents/frigate/config/config.yaml:/config/config.yaml
      - ${HOME}/Documents/frigate/storage:/media/frigate
      - type: tmpfs # 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # Port used by the Web UI
      - "554:554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "useyourownpassword!"
      LIBVA_DRIVER_NAME: "radeonsi"
